name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/myapp
          git pull origin main
          ./gradlew build -x test
          sudo docker build -t myapp .
          sudo docker rm -f springapp || true
          sudo docker run -d -p 80:8080 --name springapp myapp
